### ISSUE TITLE
ClassMethod FormatXML does not exists

### ISSUE THREAD

**Issue by gevorg95** [bdeboe/isc-iknow-setanalysis#1]
`set tString = ##class(%DeepSee.PMML.Builder.AbstractBuilder).FormatXML(tString)  ` 
ClassMethod FormatXML was deleted of  %DeepSee.PMML.Builder.AbstractBuilder class.
Location: `##class(Demo.SetAnalysis.Utils).CreateDomainDefinition(...)
`

**Comment by bdeboe** [comment]
Looks like my code for checking the version (and where that FormatXML helper method went) was a little off. Should have been fixed with the latest commit.
